### PR TITLE
feat: Add colors for bracket matching

### PR DESCRIPTION
**Pull request by scaryrawr**
- Adding colors for August 2021 [fast bracket pair colorization](https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization)

Default Colors:
image

[Samurai Doge](https://galopes.artstation.com/projects/rAGoB5) - [haishoku](https://github.com/LanceGin/haishoku) colors:
image

### CODE REVIEW

**Comment by scaryrawr** [comment]
@dlasagno depending on the wallpaper and the pywal backend, some of the colors for brackets can be close in color where the differences don't stand out as much. I don't know if it's a big issue, but just wanted to draw awareness to it.

**Comment by dlasagno** [comment]
@scaryrawr Thank you again for your precious help.
I think that the colors won't be a big issue since all the theme has the same issue for similar colors. The only thing that I don't get is why you lightened the colors.
Anyway, I'll merge the update in as soon as I can, but I will be busy for the next two days.

**Comment by scaryrawr** [comment]
> @scaryrawr Thank you again for your precious help.
> I think that the colors won't be a big issue since all the theme has the same issue for similar colors. The only thing that I don't get is why you lightened the colors.
> Anyway, I'll merge the update in as soon as I can, but I will be busy for the next two days.

No rush.

The lightening was just an attempt to have the brackets be different from key words if they ended up using the same color in some places (such as `if`). I'm wondering if there's a better way to make the colors slightly more unique without lightening them?

**Comment by dlasagno** [comment]
I see 2 other options:
- use transparency, tough I'm not sure the result will be good
- use contrast, again, I'm not really sure of the result

We should test all 3 and decide which one looks better, and no one looks good, we can stick with the plain color.

**Comment by dlasagno** [comment]
I decided to remove the lightening of colors because it wouldn't work on themes with already light colors.

**Pull request merged**
